### ISSUE TITLE
Не справедливо по поводу дз 1 лекции. Хотел красивее все сделать, с условиями if, else а получил незачет. опыт в программировании у меня есть на языке MQL4

### ISSUE THREAD

**Issue by BlackRider116** [BlackRider116/JS-Repository#10]
https://github.com/BlackRider116/JS-Repository/blob/44f79583514890fa23d8ac05d5f8730cab64daac/sportmaster%20v%202/sportmasterV2.js#L1-L7

**Comment by coursar** [comment]
К if'ам претензий насколько я помню - не было.

Это первое, второе - если ошибки появились после исправления замечаний второй попытки - ничего страшного, сдавайте ещё раз.

Третье - договаривались, что на каждый проект, отдельный репозиторий.

**Comment by BlackRider116** [comment]
на 2 лекции договорились что на каждый проект 1 репозиторий. после 1 лекции задача была понять что куда нажимать))
