### ISSUE TITLE
Поправьте оформление кода

### ISSUE THREAD

**Issue by coursar** [BlackRider116/JS-Repository#11]
https://github.com/BlackRider116/JS-Repository/blob/09bf99a2e2f5c4e0da3ef10510f674fc19bf766d/sportmaster/sportmaster.js#L5-L15

**Comment by coursar** [comment]
Почему всё куда-то уехало?

**Comment by BlackRider116** [comment]
https://github.com/BlackRider116/JS-Repository/blob/56d18400df89dc3643d616bbbb5abb975adf7197/sportmaster/sportmaster.js#L1-L7

**Comment by BlackRider116** [comment]
убрал все лишнее) не буду больше что то свое добавлять)

**Comment by coursar** [comment]
Если сделали issue - закрывайте коммитом, в видео же описано как
