### ISSUE TITLE
Убирать ненужные комментарии

### ISSUE THREAD

**Issue by coursar** [BlackRider116/JS-Repository#12]
https://github.com/BlackRider116/JS-Repository/blob/56d18400df89dc3643d616bbbb5abb975adf7197/sportmaster/sportmaster.js#L1

**Comment by BlackRider116** [comment]
https://github.com/BlackRider116/JS-Repository/blob/90270f3519a103d3fc5a39ef03513a216563268d/sportmaster/sportmaster.js#L1-L5

**Comment by BlackRider116** [comment]
удалил. Этот коммент я для себя держал по идее)

**Comment by coursar** [comment]
Код - не ваш, он общий ))
