### ISSUE TITLE
ДЗ исправлено. в таком виде формула работает исправно. (Значение (1563) - остаток от деления на 1000 (563)) / 10  = 100

### ISSUE THREAD

**Issue by BlackRider116** [BlackRider116/JS-Repository#6]
https://github.com/BlackRider116/JS-Repository/blob/15ac29808f68a8bf469ba9abe988d105d43a9d76/sportmaster/sportmaster.js#L14

**Comment by coursar** [comment]
Нужно пофиксить все открытые issue
